# -*- coding: utf-8 -*-
# Copyright 2024 Trackedge <https://trackedgetechnnologies.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    'name': 'Trackedge Product',
    'version': '14.0.0.0.1',
    'category': 'Stock',
    'sequence': 1,
    'summary': 'Trackedge trackedge Bundle',
    'author': 'Trackedge',
    'depends': [
        'base',
        'stock',
        'uom',
        'stock_change_qty_reason',
        'product_state',
        'product_pack',
        'trackedge_base',
        'stock_available',
        'stock_available_immediately',
        'stock_available_unreserved',
        'product_image_multiple',
        'stock_reserve_state',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/trackedge_product_class.xml',
        # 'data/decimal_precisions_data.xml',
        'views/item_oem.xml',
        'views/uom_uom.xml',
        'views/uom_category.xml',
        'views/product_classification.xml',
        'views/item_type.xml',
        'views/system_category.xml',
        'views/system_type.xml',
        'views/technology_type.xml',
        'views/item_voltage.xml',
        'views/item_frequency.xml',
        'views/item_category.xml',
        'views/product_template.xml',
        'views/product_product.xml',
        'wizards/stock_warehouse_orderpoint_wizard.xml',
        'views/product_state.xml',
        'views/product_pack_line.xml'
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
